alias gc="git commit"
alias gp="git push"
alias gd="git diff"
alias shred="shred -u"
alias xc="xclip -selection clipboard"
alias tmux="TMUX= tmux"
alias hidpi="gsettings set org.gnome.desktop.interface scaling-factor 2 && xrandr --output eDP1 --scale 1x1"
alias midpi="gsettings set org.gnome.desktop.interface scaling-factor 2 && xrandr --output eDP1 --scale 1.5x1.5"
alias lodpi="gsettings set org.gnome.desktop.interface scaling-factor 1 && xrandr --output eDP1 --scale 1x1"
