alias gb="gitmakebranch"
alias gc="git commit"
alias gp="git push"
alias gd="git diff"
alias shred="shred -u"
alias xc="xclip -selection clipboard"
alias tmux="TMUX= tmux"
alias hidpi="gsettings set org.gnome.desktop.interface scaling-factor 2"
alias lodpi="gsettings set org.gnome.desktop.interface scaling-factor 1"
alias unetbootin="sudo QT_X11_NO_MITSHM=1 unetbootin"
alias bfg="java -jar /home/cjr/bin/bfg-1.12.16.jar"
alias traceroute="echo \"========== Consider using tcptraceroute ==========\" && traceroute"
alias timestamp="perl -pe 's/(\d+)/localtime($1)/e'"
alias xo="xdg-open"
